version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: catalyst_db
    environment:
      POSTGRES_USER: diya-catalyst
      POSTGRES_PASSWORD: Abid090300
      POSTGRES_DB: catalystDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  scraper-engine:
    build:
      context: ./scraper-engine
      dockerfile: Dockerfile
    container_name: catalyst_scraper_engine
    environment:
      - DATABASE_URL=postgresql://diya-catalyst:Abid090300@postgres-db:5432/catalystDB
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
